import os
import json
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go

# --- Page Configuration ---
st.set_page_config(
    page_title="HeliosAI - Solar Power Generation Forecast",
    page_icon="☀️",
    layout="wide",
    initial_sidebar_state="expanded",
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(BASE_DIR, "solar_power_dataset.csv")
MODEL_PATH = os.path.join(BASE_DIR, "models", "best_solar_model.pkl")
BASELINE_PATH = os.path.join(BASE_DIR, "models", "linear_baseline_model.pkl")
METRICS_PATH = os.path.join(BASE_DIR, "models", "metrics.json")


@st.cache_data
def load_dataset():
    if os.path.exists(DATA_PATH):
        return pd.read_csv(DATA_PATH)
    return None


@st.cache_resource
def load_models_and_metrics():
    best_model = joblib.load(MODEL_PATH) if os.path.exists(MODEL_PATH) else None
    baseline_model = joblib.load(BASELINE_PATH) if os.path.exists(BASELINE_PATH) else None
    metrics = None
    if os.path.exists(METRICS_PATH):
        with open(METRICS_PATH, "r", encoding="utf-8") as f:
            metrics = json.load(f)
    return best_model, baseline_model, metrics


df = load_dataset()
best_model, baseline_model, metrics_data = load_models_and_metrics()

# --- Custom Styling ---
st.markdown("""
<style>
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #B45309;
        margin-bottom: 0.2rem;
    }
    .sub-title {
        font-size: 1.05rem;
        color: #4B5563;
        margin-bottom: 1.5rem;
    }
    .metric-card {
        background-color: #FFFBEB;
        border-radius: 12px;
        padding: 1.2rem;
        border: 1px solid #FDE68A;
        box-shadow: 0 2px 4px rgba(0,0,0,0.03);
    }
    .badge-peak {
        background-color: #DCFCE7;
        color: #166534;
        padding: 4px 10px;
        border-radius: 6px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-mod {
        background-color: #FEF3C7;
        color: #92400E;
        padding: 4px 10px;
        border-radius: 6px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-low {
        background-color: #FFEDD5;
        color: #9A3412;
        padding: 4px 10px;
        border-radius: 6px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-idle {
        background-color: #F1F5F9;
        color: #475569;
        padding: 4px 10px;
        border-radius: 6px;
        font-weight: 600;
        font-size: 0.85rem;
    }
</style>
""", unsafe_allow_html=True)

# --- Sidebar ---
st.sidebar.title("☀️ HeliosAI")
st.sidebar.markdown(
    "**Clean Energy & Photovoltaic Power Forecasting Platform**\n\n"
    "Predict electrical AC power output generated by solar plants based on ambient atmospheric and solar irradiance sensors."
)

st.sidebar.markdown("---")
st.sidebar.markdown("### 📥 Kaggle Dataset Source")
st.sidebar.markdown(
    "[**Kaggle: Solar Power Generation Data**](https://www.kaggle.com/datasets/anikannal/solar-power-generation-data)"
)
st.sidebar.caption("High-resolution telemetry capturing 34 days of inverter and weather sensor readings (45,680 records).")

st.sidebar.markdown("---")
st.sidebar.markdown("### 🏆 Champion Model")
if metrics_data:
    st.sidebar.info(
        f"**Algorithm:** {metrics_data.get('best_model')}\n\n"
        f"**Test $R^2$ Score:** {metrics_data['benchmark'][metrics_data['best_model']]['test_r2']}\n\n"
        f"**Test MAE:** {metrics_data['benchmark'][metrics_data['best_model']]['test_mae_kw']} kW\n\n"
        f"**Daytime MAPE:** {metrics_data['benchmark'][metrics_data['best_model']]['daytime_mape_pct']}%"
    )

# --- Header ---
st.markdown('<div class="main-title">☀️ HeliosAI: Solar Power Generation Forecasting</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">Physics-Informed Clean Tech Machine Learning & Grid Integration Engine</div>', unsafe_allow_html=True)

# --- Main Tabs ---
tab1, tab2, tab3 = st.tabs([
    "⚡ Power Forecaster",
    "📈 Solar Plant Analytics (EDA)",
    "🔬 Model Benchmarking & Sensor Importance"
])

# ==========================================
# TAB 1: POWER FORECASTER
# ==========================================
with tab1:
    st.markdown("### 🎛️ Real-Time Environmental Telemetry & Output Predictor")
    st.write("Tune the environmental sensors and operating parameters to forecast photovoltaic alternating current (AC) power delivery.")

    col1, col2 = st.columns([1, 1], gap="large")

    with col1:
        st.subheader("Environmental Sensors")

        preset = st.selectbox(
            "Select Weather Preset (Optional Quick Setup)",
            options=["Custom", "Peak Summer Afternoon (Clear Sky)", "Overcast / Diffuse Daylight", "Early Morning Dawn", "Nighttime (Standby)"]
        )

        # Default values according to presets
        if preset == "Peak Summer Afternoon (Clear Sky)":
            def_irr, def_amb, def_mod, def_hour, def_yield = 0.95, 34.0, 56.0, 13, 5200.0
        elif preset == "Overcast / Diffuse Daylight":
            def_irr, def_amb, def_mod, def_hour, def_yield = 0.22, 27.0, 31.0, 11, 1800.0
        elif preset == "Early Morning Dawn":
            def_irr, def_amb, def_mod, def_hour, def_yield = 0.05, 22.0, 23.5, 6, 120.0
        elif preset == "Nighttime (Standby)":
            def_irr, def_amb, def_mod, def_hour, def_yield = 0.00, 20.0, 19.5, 22, 7500.0
        else:
            def_irr, def_amb, def_mod, def_hour, def_yield = 0.72, 31.0, 47.5, 12, 3600.0

        irradiation = st.slider("Solar Irradiation (kW/m²)", min_value=0.0, max_value=1.25, value=def_irr, step=0.01, help="Incident solar flux density per square meter.")
        ambient_temp = st.slider("Ambient Temperature (°C)", min_value=15.0, max_value=45.0, value=def_amb, step=0.5, help="Surrounding outdoor air temperature.")
        module_temp = st.slider("PV Module Temperature (°C)", min_value=15.0, max_value=70.0, value=def_mod, step=0.5, help="Surface temperature of solar panels.")

        temp_diff = round(module_temp - ambient_temp, 2)
        st.caption(f"Calculated Thermal Differential (Module - Ambient): **{temp_diff:+.1f} °C**")

        c_a, c_b = st.columns(2)
        with c_a:
            hour = st.slider("Hour of Day (24h)", min_value=0, max_value=23, value=def_hour, step=1)
        with c_b:
            daily_yield = st.number_input("Accumulated Day Yield (kWh)", min_value=0.0, max_value=10000.0, value=def_yield, step=100.0)

    with col2:
        st.subheader("Grid Power Output Forecast")

        if best_model is not None:
            input_df = pd.DataFrame([{
                "ambient_temperature": ambient_temp,
                "module_temperature": module_temp,
                "temp_diff": temp_diff,
                "irradiation": irradiation,
                "daily_yield": daily_yield,
                "hour": hour
            }])

            pred_ac = max(0.0, float(best_model.predict(input_df)[0]))
            base_ac = max(0.0, float(baseline_model.predict(input_df)[0])) if baseline_model else None

            # Operational Status Classification
            if irradiation <= 0.001 or pred_ac < 1.0:
                status_badge = '<span class="badge-idle">STANDBY / NIGHT</span>'
                status_desc = "Zero irradiance. Inverter is in idle standby mode."
            elif irradiation < 0.25:
                status_badge = '<span class="badge-low">LOW YIELD</span>'
                status_desc = "Sub-optimal diffuse light (dawn, dusk, or heavy clouds)."
            elif irradiation < 0.65:
                status_badge = '<span class="badge-mod">MODERATE GENERATION</span>'
                status_desc = "Standard generation under partial sun."
            else:
                status_badge = '<span class="badge-peak">PEAK HARVEST</span>'
                status_desc = "High-irradiance regime delivering optimal electrical feed."

            # Result Display Card
            st.markdown(f"""
            <div class="metric-card">
                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <span style="font-size: 0.95rem; font-weight: 600; color: #78350F;">FORECASTED AC GRID OUTPUT</span>
                    {status_badge}
                </div>
                <div style="font-size: 2.4rem; font-weight: 800; color: #B45309; margin: 0.3rem 0;">
                    {pred_ac:,.2f} <span style="font-size: 1.2rem; font-weight: 600;">kW</span>
                </div>
                <div style="font-size: 0.9rem; color: #92400E;">
                    {status_desc}
                </div>
            </div>
            """, unsafe_allow_html=True)

            # Model Variance
            if base_ac is not None:
                st.markdown("<br>", unsafe_allow_html=True)
                diff = pred_ac - base_ac
                m1, m2 = st.columns(2)
                with m1:
                    st.metric("Champion Model (GBDT)", f"{pred_ac:,.1f} kW")
                with m2:
                    st.metric("Linear Baseline", f"{base_ac:,.1f} kW", delta=f"{diff:+,.1f} kW vs Ensemble")

            # Clean Energy Metrics
            homes = round(pred_ac / 1.2, 1) if pred_ac > 0 else 0
            co2_kg = round(pred_ac * 0.82, 1) if pred_ac > 0 else 0
            st.markdown("---")
            st.markdown("#### 🌿 Clean Grid Impact Equivalents")
            e1, e2 = st.columns(2)
            with e1:
                st.metric("🏡 Homes Powered Simultaneously", f"~{homes:,.0f} homes", help="Based on average 1.2 kW continuous household load.")
            with e2:
                st.metric("💨 Avoided Carbon Emissions", f"~{co2_kg:,.1f} kg CO₂/hr", help="Based on 0.82 kg CO2/kWh thermal grid displacement.")

            # Gauge Chart
            gauge_fig = go.Figure(go.Indicator(
                mode="gauge+number",
                value=pred_ac,
                number={"suffix": " kW", "valueformat": ",.0f"},
                gauge={
                    "axis": {"range": [0, 1450], "ticksuffix": " kW"},
                    "bar": {"color": "#D97706"},
                    "steps": [
                        {"range": [0, 200], "color": "#FEF3C7"},
                        {"range": [200, 800], "color": "#FDE68A"},
                        {"range": [800, 1450], "color": "#DCFCE7"},
                    ],
                    "threshold": {
                        "line": {"color": "green", "width": 4},
                        "thickness": 0.75,
                        "value": 1100,
                    }
                },
                title={"text": "Plant Capacity Utilization"}
            ))
            gauge_fig.update_layout(height=250, margin=dict(l=20, r=20, t=40, b=10))
            st.plotly_chart(gauge_fig, use_container_width=True)

        else:
            st.error("Model artifacts not found. Run `python train.py` first.")

# ==========================================
# TAB 2: EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================
with tab2:
    st.markdown("### 📊 Solar Plant Telemetry & Physical Analytics")
    if df is not None:
        # KPI Row
        k1, k2, k3, k4 = st.columns(4)
        with k1:
            st.metric("Telemetry Data Points", f"{len(df):,}")
        with k2:
            st.metric("Peak AC Power Recorded", f"{df['ac_power'].max():,.1f} kW")
        with k3:
            st.metric("Max Recorded Irradiance", f"{df['irradiation'].max():.3f} kW/m²")
        with k4:
            st.metric("Max Module Temperature", f"{df['module_temperature'].max():.1f} °C")

        st.markdown("---")

        c1, c2 = st.columns(2)
        with c1:
            st.markdown("#### 1. Daily Diurnal Generation Curve (24-Hour Solar Cycle)")
            hourly_avg = df.groupby("hour")[["ac_power", "irradiation"]].mean().reset_index()
            fig1 = px.line(
                hourly_avg,
                x="hour",
                y="ac_power",
                markers=True,
                labels={"hour": "Hour of Day (0-23)", "ac_power": "Average AC Power (kW)"},
                title="Bell-Shaped Daily Solar Generation Profile",
            )
            fig1.update_traces(line_color="#D97706", line_width=3)
            fig1.update_layout(height=380)
            st.plotly_chart(fig1, use_container_width=True)

        with c2:
            st.markdown("#### 2. Solar Irradiation vs Power Generation")
            sample_df = df.sample(min(3000, len(df)), random_state=42)
            fig2 = px.scatter(
                sample_df,
                x="irradiation",
                y="ac_power",
                color="module_temperature",
                color_continuous_scale="Viridis",
                labels={"irradiation": "Irradiation (kW/m²)", "ac_power": "AC Power (kW)", "module_temperature": "Module Temp (°C)"},
                title="Linear Photovoltaic Response with Thermal Saturation",
            )
            fig2.update_layout(height=380)
            st.plotly_chart(fig2, use_container_width=True)

        c3, c4 = st.columns(2)
        with c3:
            st.markdown("#### 3. Thermal Gradient (Module vs Ambient Temperature)")
            fig3 = px.scatter(
                sample_df,
                x="ambient_temperature",
                y="module_temperature",
                color="irradiation",
                color_continuous_scale="Inferno",
                labels={"ambient_temperature": "Ambient Temp (°C)", "module_temperature": "PV Module Temp (°C)", "irradiation": "Irradiance"},
                title="High Solar Irradiance Elevates Module Temp Above Ambient",
            )
            fig3.update_layout(height=380)
            st.plotly_chart(fig3, use_container_width=True)

        with c4:
            st.markdown("#### 4. Distribution of Inverter Power Output")
            fig4 = px.histogram(
                df[df["ac_power"] > 10.0],
                x="ac_power",
                nbins=40,
                color_discrete_sequence=["#F59E0B"],
                labels={"ac_power": "AC Power Output (kW)"},
                title="Daytime Active Generation Distribution",
            )
            fig4.update_layout(height=380)
            st.plotly_chart(fig4, use_container_width=True)

        with st.expander("🔍 View Raw Plant Sensor Telemetry Records"):
            st.dataframe(df.head(1000), use_container_width=True)
    else:
        st.warning("`solar_power_dataset.csv` not found.")

# ==========================================
# TAB 3: MODEL COMPARISON & SENSOR INSIGHTS
# ==========================================
with tab3:
    st.markdown("### 🔬 Multi-Model Benchmark & Sensor Feature Importance")
    st.write(
        "In the reference housing script, only a single feature (`area`) was evaluated using basic linear regression. "
        "Here, we systematically evaluate 4 distinct machine learning algorithms on 45,680 real-world sensor records."
    )

    if metrics_data:
        benchmark = metrics_data.get("benchmark", {})
        bench_df = pd.DataFrame.from_dict(benchmark, orient="index").reset_index()
        bench_df.rename(columns={
            "index": "Model Architecture",
            "cv_r2_mean": "5-Fold CV R²",
            "test_r2": "Test R² Score",
            "test_mae_kw": "Test MAE (kW)",
            "test_rmse_kw": "Test RMSE (kW)",
            "daytime_mape_pct": "Daytime MAPE (%)",
        }, inplace=True)

        st.dataframe(
            bench_df.style.highlight_max(subset=["Test R² Score", "5-Fold CV R²"], color="#DCFCE7")
            .highlight_min(subset=["Test MAE (kW)", "Test RMSE (kW)", "Daytime MAPE (%)"], color="#DCFCE7")
            .format({
                "5-Fold CV R²": "{:.4f}",
                "Test R² Score": "{:.4f}",
                "Test MAE (kW)": "{:.2f} kW",
                "Test RMSE (kW)": "{:.2f} kW",
                "Daytime MAPE (%)": "{:.2f}%",
            }),
            use_container_width=True
        )

        m_col1, m_col2 = st.columns(2)

        with m_col1:
            st.markdown("#### Test Accuracy ($R^2$ Score)")
            fig_bar = px.bar(
                bench_df,
                x="Model Architecture",
                y="Test R² Score",
                color="Test R² Score",
                color_continuous_scale="Viridis",
                text="Test R² Score",
                title="Model Accuracy Comparison (Test R²)",
            )
            fig_bar.update_traces(texttemplate="%{text:.4f}", textposition="outside")
            fig_bar.update_layout(yaxis=dict(range=[0.97, 1.0]), height=380)
            st.plotly_chart(fig_bar, use_container_width=True)

        with m_col2:
            st.markdown("#### Test Error Comparison (MAE in kW)")
            fig_mae = px.bar(
                bench_df,
                x="Model Architecture",
                y="Test MAE (kW)",
                color="Test MAE (kW)",
                color_continuous_scale="Reds_r",
                text="Test MAE (kW)",
                title="Mean Absolute Error in Kilowatts (Lower is Better)",
            )
            fig_mae.update_traces(texttemplate="%{text:.2f} kW", textposition="outside")
            fig_mae.update_layout(height=380)
            st.plotly_chart(fig_mae, use_container_width=True)

        # Feature Importance
        st.markdown("---")
        st.markdown("#### 🎯 Physical Sensor Feature Importance Ranking (Champion GBDT)")
        feat_imp = metrics_data.get("feature_importances", {})
        if feat_imp:
            f_df = pd.DataFrame(list(feat_imp.items()), columns=["Sensor Feature", "Importance"])
            f_df["Percentage"] = f_df["Importance"] * 100
            f_df = f_df.sort_values(by="Importance", ascending=True)

            fig_imp = px.bar(
                f_df,
                x="Percentage",
                y="Sensor Feature",
                orientation="h",
                color="Percentage",
                color_continuous_scale="YlOrBr",
                labels={"Percentage": "Relative Importance (%)", "Sensor Feature": "Telemetry Feature"},
                title="Sensor Drivers of Photovoltaic AC Power Generation",
            )
            fig_imp.update_layout(height=380)
            st.plotly_chart(fig_imp, use_container_width=True)

        st.markdown(r"""
        > **Clean Tech Takeaway:** Solar irradiation accounts for **99.5%** of primary energy input. However, non-linear ensemble models (Gradient Boosting and Random Forest) achieve a **33% reduction in Mean Absolute Error (from 25.68 kW down to 17.18 kW)** compared to basic linear models because they accurately account for thermal saturation in PV cells when module temperatures exceed ambient temperatures by $20^\circ\text{C}+$.
        """)
    else:
        st.warning("No benchmark data found. Run `python train.py` first.")
